name: firebaseapi
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  image_picker: ^1.1.2
  provider: ^6.1.2
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  google_maps_flutter: ^2.10.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true
  assets:
    - assets/
