name: firebaseapi
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  card_swiper: ^3.0.1
  flutter:
    sdk: flutter
  http: ^1.3.0
  provider: ^6.1.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true
  assets:
    - assets/
