name: loginform
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  flutter:
    sdk: flutter
  provider: ^6.1.2

flutter:
    uses-material-design: true

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
